### ISSUE TITLE
Duplicate logs in jupyter notebook

### ISSUE THREAD

**Issue by nathlacroix** [QudevETH/PycQED_py3#12]
Logs are dupplicated many times when using jupyter notebook. This reduces readability and slows down the execution of the code.

**Comment by antsr** [comment]
Initial testing seems to indicate that the issue is with the `log.addHandler(logging.StreamHandler())` commands throughout the package.

**Comment by antsr** [comment]
But there might be some quirks depending on whether the logger is initialized in a notebook or from an init script

**Comment by antsr** [comment]
We should also come up with a clear idea how we determine the message levels (e.g. error vs warning vs info vs debug).
My first idea is that by default we print only info and lower messages to the jupyter notebook.
All debugging related meassages (e.g. print parameter values) would by default be hidden, but can be enabled per-module basis by registering a handler in the notebook.

**Comment by antsr** [comment]
What would you like to see in the message stream in the jupyter notebook? 
@nathlacroix @Vintrix @michele-cc @jo3141 @MichKe95

**Comment by nathlacroix** [comment]
#11 Seems that the duplicating issue has been fixed in merge with master, thanks to @Vintrix adding name to loggers in all files. i.e. `log = logging.getLogger(__name__)` instead of `logging.getLogger()`, which added new root loggers resulting in duplicates. 

We could close this issue and reopen a new one for the message levels ? It is typically easier to browse through issue afterward if we stay very specific :)

**Comment by antsr** [comment]
:+1: Thats good to hear. Lets continue the discussion in a new issue, i agree
