### ISSUE TITLE
Create a virtual backend for pycqed

### ISSUE THREAD

**Issue by nathlacroix** [QudevETH/PycQED_py3#73]
Currently, debugging and development of features in pycqed may require a physical setup. Enabling a fully virtual backend would significantly increase the capabilities of pycqed, as it would improve the workflow of developers and users, and ultimately result into a more efficient usage of physical setups.

**Comment by nathlacroix** [comment]
Initial brainstorm ideas by @grahamnorris :
Have some sort of global variable (or whatever the proper alternative is) in the init script, something like pycqed.backend = 'virtual' or pycqed.backend = 'physical' that then configures all the instruments in the correct mode.

- [ ] For qcodes, there is pyVISA-sim for creating simulated instruments (https://github.com/QCoDeS/pyvisa-sim). I hope that by selecting this as the backend, we can create simulated forms of the MWG, SRS SIM9000, etc. rather easily

- [ ] For ZI instruments, there is already the server = emulated option, although AFICR, this might not work on the PQSC

- [ ] The UCboard and switch control drivers would have to be updated. As part of this, I would prefer to remove the dependency on NI's daqmx module which is windows only

**Comment by chellings** [comment]
I meanwhile have a preliminary version of a virtual switch driver. We are still lacking a virtual driver for the Agilent trigger box. The virtual DC source driver still needs an update to support the same parameters as the physical driver.
